### ISSUE TITLE
Recommended way of styling invisible characters?

### ISSUE THREAD

**Issue by chriscalo** [coderaiser/cm-show-invisibles#8]
I've been looking for a way of showing invisible characters, so thanks for creating this add-on. 🙏

What's the recommended means of styling invisible characters? I find the default to be far too dark, and it appear that color is hard-coded in a way that seems to not be overridable:

```js
function getStyle() {
    const style = [
        '.cm-whitespace::before {',
        '    position: absolute;',
        '    pointer-events: none;',
        '    color: #404F7D;',
        '}'
    ].join('');
    
    return style;
}

function getEOL() {
    const style = [
        '.CodeMirror-code > div > pre > span::after, .CodeMirror-line > span::after {',
        '    pointer-events: none;',
        '    color: #404F7D;',
        '    content: "¬"',
        '}',
    ].join('');
    
    return style;
}
```

**Comment by coderaiser** [comment]
So you want to change invisible character from `¬` to something else? It is possible to add such an option to `cm-show-invisibles` with help of [cm.getOption](https://github.com/coderaiser/cm-show-invisibles/blob/v2.0.2/lib/show-invisibles.js#L19).

It is a great idea for a pull request :).

**Comment by chriscalo** [comment]
@coderaiser, no, I was asking about how to change the color of the invisibles:

```css
.cm-whitespace::before {
  /* … */
  color: #404F7D; /* <= I want to customize this color */
}

.CodeMirror-code > div > pre > span::after, .CodeMirror-line > span::after {
  /* … */
  color: #404F7D; /* <= I want to customize this color */
  /* … */
}
```

However, I was able to find an alternative approach, so I'll go ahead and close this issue. Thanks!
